# Do this only once per namespace
# For example multiple clusters in the same namespace,
# just do this before creating the first one
#
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSClusterControllerIdentity
metadata:
  name: default
  namespace: ${NAMESPACE}
spec:
  allowedNamespaces:
    list:
    - ${NAMESPACE}